# Generated by Django 4.1.7 on 2023-03-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0002_movies_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
